Deno.test("StepFirst", () => { })
Deno.test("StepFirst Layer 1", () => { })
Deno.test("StepFirst Layer 2", () => { })
Deno.test("StepAfter Layer 0 Zweite Node", () => { })
Deno.test("StepAfter Layer 1 Zweite Node", () => { })
Deno.test("StepAfter Gleiche Position sollte nichts ändern", () => { })
Deno.test("StepFirst in Branch sollte gehen", () => { })
Deno.test("Fehler: StepAfter in sich selber (if branch)", () => { })
